# Site settings
title: "Prashant Solanki's Blog"
header-img: "img/home-bg.jpg"
email: "prashants975@gmail.com"
description: ""
baseurl: ""
url: "http://prashants975.github.io"
github_username: "prashants975"

# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 10
timezone: "Asia/Delhi"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
plugins: ["jekyll-paginate", "jekyll-sitemap"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
